sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IbyRQXL9xf3mdCJ2hHXnfT+UfpNUhZrBl2eQqjgbyqGFk57zBnIbS5tou3CBMhU93Q10ezUKnclIsIFcXXRI7ONxuYa4t3QM6LNqBlre4xJJh/hXXvDAnMsTM3P6eeaoSUJI5Uv5Nlni970oEEB+2j67iVopo5wRYKxH9aeJ4Yuz8DgrVeLqo8lflVK2EljsSGqwblLLkrKXtTIIYX7IFycUd4+jJhb+55bWGh01iepTkDBOTjjWfYUdvjgKmR/PZBr+VCyvKaeOeAsKhlH6KSVDbJZYVn3t9VFCbKW8Qapu10D2qv0+oj+Xibfw42M0IDem7/nTt5zxL7LLM6OmPkA/x1rnub0GAPien/SLvUhmFxz8Kcoxknbs/I4l4mAM4NaGxCnpI3MkKy7pJuPPgECNmPk4dPg2BwzZr+sWXaqF38KPMBc/vCZHqrrl14Tu5LNMw6CtWGoxu5f+GuJE4rIgvlGxLip2HuU3G50G7k+OuJoAi9ZHEenK+Qg7Z6AAYLQ9Mv5s377G2dXwerYVxkUwZKd+s7osErVQ2prR7TdGXqM7bu9E2LhPPwGg4s84WscHS27SkG1ggoiIpjLsMkeWyf4X5xxzcyr+FQ0iRmeugp+LLd9VKRR3AdYJ6pnWLkWgpM3aS2X27OKXfW8chl5Fvyl9u57/rWCIbN9EmHU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Definitions-Essays-in-Contemporary-Criticism-First-Series_6106
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy